version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wg
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./wg-config:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      - vpn_net
 
  emqx:
    image: emqx:latest
    container_name: emqx
    restart: unless-stopped
    environment:
      EMQX_NODE__NAME: gatecontroller_emqx@emqx
    ports:
      - "1883:1883"    # MQTT
      - "8083:8083"    # WebSocket
      - "8084:8084"    # Secure WebSocket
      - "8081:8081"    # HTTP API
      - "18083:18083"  # Web dashboard
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    networks:
      - vpn_net
      - default

volumes:
  emqx-data:
  emqx-log:

networks:
  vpn_net:
