version: '3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    depends_on:
      - mqtt-broker
      - mqtt-client
    environment:
      - MQTT_BROKER_HOST=mqtt-broker

  mqtt-broker:
    build:
      context: ../mqtt_broker
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    ports:
      - "1883:1883"

  mqtt-client:
    build: 
      context: ../mqtt_client
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    depends_on:
      - mqtt-broker
    links:
      - mqtt-broker
    environment:
      - MQTT_BROKER_HOST=mqtt-broker