version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    environment:
      - MQTT_BROKER_HOST=emqx

  emqx:
    image: emqx:latest
    restart: always
    environment:
      EMQX_NODE__NAME: gatecontroller_emqx@emqx
    ports:
      - "1883:1883"    # MQTT port
      - "8083:8083"    # WebSocket port
      - "8084:8084"    # Secure WebSocket port
      - "8081:8081"    # HTTP API port
      - "18083:18083"  # Management Console port
    volumes:
      - ../mqtt_broker/data:/opt/emqx/data
      - ../mqtt_broker/log:/opt/emqx/log

