# credentialserver configuration
MQTT_BROKER = "tcp://192.168.1.29:1883"
LOCATION_ID = "pigate-speedway-self-storage"
REMOTE_DB_TABLE = "Credentials"
FILE_WATCHER_PATH = "C:\\Users\\steph\\Gate Sync"

DB_HOST = "192.168.1.29"
DB_PORT = "5432"                    
DB_NAME = "pigate_db"                 
DB_USER = "pigate_user"      
DB_PASSWORD_ENV = "PIGATE_DB_PASSWORD" # Environment variable for DB password
