# credentialserver configuration
MQTT_BROKER = "tcp://192.168.1.29:1883"
LOCATION_ID = "pigate-speedway-self-storage"
REMOTE_DB_TABLE = "credentials"
FILE_WATCHER_PATH = "C:\\Users\\PiGateServer\\Documents\\piGateCreds"