version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pigate_db
      POSTGRES_USER: pigate_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/New_York
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vpn_net
      - default

volumes:
  postgres-data:

networks:
  vpn_net:
  