# .github/workflows/deploy-mqtt.yml
name: Deploy MQTT Broker & Credential Server

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'pigate/cmd/credentialserver/**'
      - 'pigate/pkg/**'
      - 'pigate/configs/credentialserver-config.toml'

jobs:
  deploy-credentialserver:
    runs-on: [ self-hosted, Windows, pigate-cred ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Credential Server
        shell: powershell
        working-directory: pigate
        run: go build -o ../credentialserver.exe ./cmd/credentialserver/main.go

      - name: Create service folder
        shell: powershell
        run: |
          $path = 'C:\Services\credentialserver'
          if (-not (Test-Path $path)) {
            New-Item -ItemType Directory -Path $path | Out-Null
          }

      - name: Copy Config and Binary to Service Directory
        run: |
          copy credentialserver.exe C:\Services\credentialserver\
          copy pigate\configs\credentialserver-config.toml C:\Services\credentialserver\

      - name: (Re)Install Windows Service
        shell: cmd
        run: |
          nssm stop credentialserver || echo "Service not found, continuing"
          nssm remove credentialserver confirm || echo "Service not found, continuing"
          nssm install credentialserver C:\Services\credentialserver\credentialserver.exe
          nssm set credentialserver AppParameters -c C:\Services\credentialserver\
          nssm start credentialserver