# .github/workflows/deploy-mqtt.yml
name: Deploy MQTT Broker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'mqtt_broker/**'
      - 'wg-config/wireguard.conf'   # so we pick up any template changes too

jobs:
  deploy-mqtt:
    runs-on: [ self-hosted, Linux, pigate-mqtt ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Inject WireGuard server private key
        working-directory: mqtt_broker/wg-config
        run: |
          sed -i "s|<SERVER_PRIVATE_KEY>|${{ secrets.WG_SERVER_PRIVATE_KEY }}|g" wireguard.conf

      - name: Deploy MQTT Broker
        working-directory: mqtt_broker
        run: |
          docker compose pull
          docker compose down || true
          docker compose up -d

      - name: Verify MQTT Broker is running
        run: |
          if ! docker ps --filter "name=emqx" --filter "status=running" | grep emqx; then
            echo "emqx container is not running!" && exit 1
          fi
          echo "emqx is up."
