# .github/workflows/deploy-mqtt.yml
name: Deploy MQTT Broker & Credential Server

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'pigate/cmd/credentialserver/**'
      - 'pigate/pkg/**'
      - 'pigate/configs/credentialserver-config.toml'

jobs:
  deploy-credentialserver:
    runs-on: [ self-hosted, Windows, pigate-cred ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Credential Server
        run: |
          go build -o credentialserver.exe ./pigate/cmd/credentialserver/main.go

      - name: Copy Config and Binary to Service Directory
        run: |
          mkdir C:\Services\credentialserver 2>NUL
          copy credentialserver.exe C:\Services\credentialserver\
          copy pigate\configs\credentialserver-config.toml C:\Services\credentialserver\

      - name: (Re)Install Windows Service
        run: |
          nssm stop credentialserver || echo "Service not found, continuing"
          nssm remove credentialserver confirm || echo "Service not found, continuing"
          nssm install credentialserver C:\Services\credentialserver\credentialserver.exe
          nssm set credentialserver AppParameters -c C:\Services\credentialserver\
          nssm start credentialserver